name: Workflow 2 - Test Before Integrate to Main

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Full Test Suite (Unit, Integration, System)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: mvn -Dtest='es.codeurjc.web.nitflex.unit.**.*' test

      - name: Run Integration Tests
        run: mvn -Dtest='es.codeurjc.web.nitflex.integration.**.*' test

      - name: Run System Tests
        run: mvn -Dtest='es.codeurjc.web.nitflex.e2e.**.*' test