name: Workflow 3 - Test After Ending Feature to Main

on:
  pull_request: # depende de si es push o pull request
    branches: [ main ]
    types: [ closed ]
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
    
permissions:
  contents: read

jobs:
  test:
    if: github.ref_name != 'main' && github.event.pull_request.merged == true # depende si es solo feature-1 o !main
    runs-on: ubuntu-latest
    name: Full Test Suite (Unit, Integration, System)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check if PR is from feature-1
        if: github.event.pull_request.head.ref != 'feature-1'
        run: echo "PR not from feature-1. Skipping ..." && exit 1
          fi

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: mvn -Dtest='es.codeurjc.web.nitflex.unit.**.*' test

      - name: Run Integration Tests
        run: mvn -Dtest='es.codeurjc.web.nitflex.integration.**.*' test

      - name: Run System Tests
        run: mvn -Dtest='es.codeurjc.web.nitflex.e2e.**.*' test
